build website:
  stage: build
  image: node:16.5.0
  script: 
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

deploy to S3:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws s3 cp build s3://$S3_SIT_BUCKET/ --recursive --exclude ".gitlab-ci.yml"
    - aws cloudfront create-invalidation --distribution-id $SIT_CLOUDFRONT_DIST --paths "/*"
