build website:
  stage: build
  image: node:16.5.0
  script: 
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

deploy to S3:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp build s3://$S3_BUCKET --recursive
